### ISSUE TITLE
最初の一歩がわからない

### ISSUE THREAD

**Issue by yomichi** [QLMS/HPhi#1]
ビルドの方法は普通のテキストファイルで書いてあった方がいいような気がします。
トップディレクトリに `README.md` とかを置くのが良いのでは？

**Comment by k-yoshimi** [comment]
ご不便をおかけして申し訳ありません。
下記にマニュアルをpdf化したファイルをあげました。
http://qlms.github.io/HPhi/manual/userguide_jp.pdf
http://qlms.github.io/HPhi/manual/userguide_en.pdf
そちらをご参照していただければと思います。
どうぞよろしくお願いいたします。
