### ISSUE TITLE
Lanczos における再計算モード

### ISSUE THREAD

**Issue by yomichi** [QLMS/HPhi#13]
`ReStart` を用いることで再計算ができるようですが、実際に使ってみても何も起きません。
マニュアルの4.3.23 には Lanczos 法のときに生成されるファイル名が書いてあるのですが、そのファイルが出てきません。
TPQ のときは問題なく動作します。

**Comment by yomichi** [comment]
あと、出力ファイル名に `zvo_` がつかないようです。

**Comment by k-yoshimi** [comment]
@yomichi 
Lanczos法については再計算モード(固有ベクトルを入力して期待値を計算するモード)については対応していますが、再計算についてはまだ対応してませんでした。また、マニュアルについて指摘してくださりありがとうございます。次のversion時に実装および修正の対応をしておくようにいたします。

**Comment by k-yoshimi** [comment]
@yomichi 
ver. 2.0で対応しました。詳細をマニュアルに記載しましたのでご確認ください。
