### ISSUE TITLE
Particle number in GC calculations

### ISSUE THREAD

**Issue by TMueller83** [QLMS/HPhi#14]
It seems, that in v2.0 the particle number is not correctly computed (or written)  in GC full diagonalisazions. For example in the case of the Fermion Hubbard-Model using the following `input` file for the Hubbard-dimer
```
model = "Fermion HubbardGC"
method = "fulldiag"
lattice = "Chain Lattice"
L = 2
U = 4
t = 1
```
running
`HPhi -s input`
produces the following `phys.dat` file
```
  <H>         <N>        <Sz>       <S2>       <D> 
  -2.472136   4.000000   0.000000   0.000000   0.276393
  -2.000000   4.000000   0.500000   0.750000   0.000000
  -2.000000   4.000000  -0.500000   0.750000   0.000000
   0.000000   4.000000   0.000000   2.000000   0.000000
   0.000000   4.000000  -1.000000   2.000000   0.000000
   0.000000   4.000000   1.000000   2.000000   0.000000
   0.000000   4.000000   0.000000   0.000000   0.000000
   2.000000   4.000000   0.500000   0.750000   1.000000
   2.000000   4.000000   0.500000   0.750000   0.000000
   2.000000   4.000000  -0.500000   0.750000   0.000000
   2.000000   4.000000  -0.500000   0.750000   1.000000
   4.000000   4.000000   0.000000   0.000000   1.000000
   6.000000   4.000000   0.500000   0.750000   1.000000
   6.000000   4.000000  -0.500000   0.750000   1.000000
   6.472136   4.000000   0.000000   0.000000   0.723607
   8.000000   4.000000   0.000000   0.000000   2.000000
```
which indicates, that each eigenstate has a total of 4 electrons.

Nevertheless, from the one-particle Greens Function of each state the correct particle number can be easily obtained, but fixing this issue would be very nice.

**Comment by k-yoshimi** [comment]
thanks for your report!
we'll fix this in the next release.

**Comment by TMueller83** [comment]
Furthermore also the averages seem not to be correct for the Hubbard dimer (L=2). I think the results would be correct for twice the hopping `t`. This could be caused, because in contrast to all other chain-lattices the dimer only has one next nearest neighbour site. For L>2 the results of the full diagonalisazion are correct for the input hopping `t`.

**Comment by k-yoshimi** [comment]
In Standard mode, we assume the periodic boundary. 
In this case, the transfer parts of the hamiltonian becomes
t (c_{0}^{\dag}c_1+h.c.) + t (c_{1}^{\dag}c_0+h.c.) = 2 t (c_{0}^{\dag}c_1+h.c.) .
This is why the hopping becomes twice for the Hubbard dimer(L=2).
So please set t/2 for the Hubbard dimer(L=2).

**Comment by TMueller83** [comment]
Okay I understand. Thank you alot!

**Comment by k-yoshimi** [comment]
@TMueller83 
Today, we released HPhi ver. 2.0.1.   
In this version, we fixed the bug reported in this issue (Thanks for the report !).
Please use this new version.

**Comment by TMueller83** [comment]
Okay, just downloaded it. Thank you very much for the fix and the new release!
