### ISSUE TITLE
奇数サイト三角格子スピン模型の二体グリーン函数がおかしい

### ISSUE THREAD

**Issue by ultimatile** [QLMS/HPhi#15]
S=1/2三角格子スピン模型で奇数サイトのときに二体グリーン函数の値が変です。
例えば、スタンダードモードで
```
a0W=3
a0L=0
a1W=0
a1L=3
model="Spin"
method="Lanczos"
lattice="triangular Lattice"
J=1.0
2Sz=1.0
```
で(N=9)各サイトi=0,...8のS_i^2を計算すると
  ``` 
0.75085532  0.73017674  0.93563461
0.93563461  0.75085532  0.73017674  
0.73017674 0.93563461  0.75085532 
```
となり、(S_i^+S_i^-+S_i^+S_i^-)/2を計算すると
``` 
0.50085532  0.48017674  0.68563461  
0.68563461  0.50085532  0.48017674 
0.48017674 0.68563461  0.50085532
```
となりました。また全スピンS_tot^2を計算すると1.25になりました。
全対角化(N=3,9)とLanczos法(N=9,12,15,21)で試しましたが同様の結果になりました。
各サイトのS_i^2は3/4((S_i^+S_i^-+S_i^+S_i^-)/2は1/2)になるはずです。
(偶数サイトの場合(N=12,18,24)はそうなっています。)

**Comment by mitsuaki1987** [comment]
@ultimatile 
報告どうもありがとうございます。
2体相関関数の計算の計算のところにバグがありましたので、直したものをリリースします。

**Comment by mitsuaki1987** [comment]
@ultimatile

バグフィックスをしたバージョンをリリースしました。
https://github.com/QLMS/HPhi/releases/tag/v2.0.2

**Comment by ultimatile** [comment]
修正ありがとうございます。
```
$bash HPhiconfig.sh intel-openmpi
$make HPhi
>CalcByFullDiag.o: In function `CalcByFullDiag':
>~/HPhi-2.0.2/src/CalcByFullDiag.c:40: undefined reference to `inputHam'
>make[2]: *** [HPhi] エラー 1
```
となりコンパイル出来ませんでした。

**Comment by k-yoshimi** [comment]
@ultimatile 
makeのコンパイルですが、
src/makefile_src
に新規ファイルの追加ミスがありました。
cmakeをお使いいただくか、
OBJSにinput.oを、HEADERSにinclude/input.hを
追加していただくとコンパイルできると思いますので、ご確認ください。

**Comment by ultimatile** [comment]
無事コンパイルでき、S_i^2も正しい値が確認できました。ありがとうございました。
