### ISSUE TITLE
1体グリーン関数の出力形式がマニュアルと違う

### ISSUE THREAD

**Issue by yomichi** [QLMS/HPhi#4]
1体グリーン関数の計算結果 `cisajs.dat` の出力形式がマニュアルと異なっている

マニュアル（とグリーン関数の定義ファイル）では `[site1] [spin1] [site2] [spin2]` という順番だが、
出力の方は `[site1] [site2] [spin1] [spin2]` となっている

**Comment by k-yoshimi** [comment]
マニュアルに合わせ、入出力形式を統一するようにしますので、対応まで今しばらくお待ち下さい。

**Comment by k-yoshimi** [comment]
ver. 0.1.1で対応しましたので、ご確認よろしくお願いします。
